In [1]:
from array import * # importing everything in array by using *
arr=array('i',[])

In [2]:
n=int(input('Enter the length of array:'))
for i in range(n):
    x=int(input('Enter the next value:'))
    arr.append(x)
print(arr)

Enter the length of array:10
Enter the next value:5
Enter the next value:6
Enter the next value:45
Enter the next value:5
Enter the next value:8
Enter the next value:8
Enter the next value:6
Enter the next value:9
Enter the next value:10
Enter the next value:15
array('i', [5, 6, 45, 5, 8, 8, 6, 9, 10, 15])


In [3]:
arr2=array('i',[])
m=int(input('Enter the length of array:'))
for i in range(5):
    y=int(input('Enter the next value:'))
    arr2.append(y)
print(arr2)
# here we specified in range upto 5 so that is why it is taking 5 values,if we replace 5 with m then
# it will take user defined values only

Enter the length of array:20
Enter the next value:02
Enter the next value:2
Enter the next value:5
Enter the next value:6
Enter the next value:6
array('i', [2, 2, 5, 6, 6])


In [4]:
arr3=array('i',[])
x=int(input('Enter the length of array:'))
for i in range(x):
    y=int(input('Enter the next value:'))
    arr3.append(y)
print(arr3)
val=int(input('Enter the value for search:'))
k=0
for e in arr3:
    if e==val:
        print(k)
        break
    k+=1
# this is correct way

Enter the length of array:5
Enter the next value:6
Enter the next value:6
Enter the next value:6
Enter the next value:68
Enter the next value:8
array('i', [6, 6, 6, 68, 8])
Enter the value for search:6
0


In [6]:
arr4=array('i',[])
x=int(input('Enter the length of array:'))
for i in range(x):
    y=int(input('Enter the next value:'))
    arr4.append(y)
print(arr4)
val=int(input('Enter the value for search:'))
k=0
for e in arr4:
    if e==val:
        print(k)
        break
    k+=1
print(arr4.index(val))

Enter the length of array:5
Enter the next value:6
Enter the next value:45
Enter the next value:8
Enter the next value:9
Enter the next value:8
array('i', [6, 45, 8, 9, 8])
Enter the value for search:9
3
3


In [9]:
from numpy import*

In [10]:
arr=array([1,2,3,4,5])

In [11]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.dtype

dtype('int32')

In [14]:
ar=linspace(0,15,16)

In [15]:
ar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [16]:
ar2=linspace(0,15,5)

In [17]:
ar2

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [18]:
ar3=arange(1,10,2)

In [19]:
ar3

array([1, 3, 5, 7, 9])

In [20]:
ar4=logspace(1,40,5)
ar4

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [21]:
ar5=zeros(5)

In [22]:
ar5

array([0., 0., 0., 0., 0.])

In [23]:
ar6=ones(10)

In [24]:
ar6

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
ar7=ones(5,int)
ar7

array([1, 1, 1, 1, 1])

In [30]:
ar7=array([1,2,3,4,5])

In [31]:
ar7

array([1, 2, 3, 4, 5])

In [32]:
ar7=ar7+5
print(ar7)

[ 6  7  8  9 10]


In [33]:
ar8=array([5,6,7,8,9])

In [34]:
ar8=ar7+ar8

In [35]:
ar8

array([11, 13, 15, 17, 19])

In [36]:
sin(ar8)

array([-0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [39]:
ar9=array([0,45,90,180,270,360])

In [40]:
sin(ar9)

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264, -0.17604595,
        0.95891572])

In [41]:
cos(ar9)

array([ 1.        ,  0.52532199, -0.44807362, -0.59846007,  0.98438195,
       -0.28369109])

In [42]:
log(ar9)

<ipython-input-42-84994450522b>:1: RuntimeWarning: divide by zero encountered in log
  log(ar9)


array([      -inf, 3.80666249, 4.49980967, 5.19295685, 5.59842196,
       5.88610403])

In [43]:
sum(ar9)

945